# Generated by Django 4.0 on 2021-12-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contato',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customusuario')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.endereco')),
            ],
            options={
                'db_table': 'demanda',
            },
        ),
    ]
